/**
 * Unified, format-agnostic exporter. Give it rows + a column spec + a format and
 * it returns a ready-to-stream body with the right mime type and extension.
 *
 *   csv / xlsx -> delegate to src/lib/utils/tabular.ts
 *   pdf        -> branded table via src/lib/pdf/document.ts
 *   json       -> pretty JSON.stringify(rows)
 *
 * Used by the payslips/reports module to back a single download endpoint.
 */
import { toCsv, toXlsx, type Column } from '@/lib/utils/tabular';
import {
  createDocument,
  drawHeader,
  drawTable,
  drawFooter,
  type PdfColumn,
} from '@/lib/pdf/document';

export type ExportFormat = 'csv' | 'xlsx' | 'pdf' | 'json';

export type ExportOptions = {
  /** Sheet name (xlsx) / brand header company name (pdf). */
  title?: string;
  /** Company/brand name shown in the PDF header. */
  companyName?: string;
  /** Footer note for the PDF. */
  footer?: string;
  /** Per-column alignment hints for the PDF table (keyed by column header). */
  align?: Record<string, 'left' | 'right'>;
};

export type ExportResult = {
  body: Uint8Array | string;
  mime: string;
  ext: 'csv' | 'xlsx' | 'pdf' | 'json';
};

/** Resolve a single cell to a display string (mirrors tabular's logic). */
function cellString<T>(row: T, col: Column<T>): string {
  if (col.format) {
    const v = col.format(row);
    return v === null || v === undefined ? '' : String(v);
  }
  const v = (row as Record<string, unknown>)[col.key as string];
  if (v === null || v === undefined) return '';
  if (v instanceof Date) return v.toISOString().slice(0, 10);
  if (typeof v === 'object') return JSON.stringify(v);
  return String(v);
}

async function toPdf<T>(
  rows: T[],
  columns: Column<T>[],
  opts: ExportOptions,
): Promise<Uint8Array> {
  const doc = await createDocument();
  const { page } = doc.addPage();

  let y = drawHeader(page, doc.fonts, {
    companyName: opts.companyName ?? opts.title ?? 'PayCore',
    title: opts.title ?? 'Export',
    subtitle: `${rows.length} record${rows.length === 1 ? '' : 's'}`,
  });

  const pdfColumns: PdfColumn[] = columns.map((c) => ({
    header: c.header,
    align: opts.align?.[c.header] ?? 'left',
  }));

  const tableRows = rows.map((row) => columns.map((col) => cellString(row, col)));
  // drawTable paginates implicitly by stacking; for very large sets the body
  // may overflow a single page. We keep the core single-page render and leave
  // multi-page chunking to the report module which knows its row counts.
  drawTable(page, doc.fonts, pdfColumns, tableRows, y);

  drawFooter(
    page,
    doc.fonts,
    opts.footer ?? `Generated by PayCore on ${new Date().toISOString().slice(0, 10)}`,
  );

  return doc.save();
}

/** Export rows in the requested format. */
export async function exportRows<T>(
  rows: T[],
  columns: Column<T>[],
  format: ExportFormat,
  opts: ExportOptions = {},
): Promise<ExportResult> {
  switch (format) {
    case 'csv':
      return {
        body: toCsv(rows, columns),
        mime: 'text/csv; charset=utf-8',
        ext: 'csv',
      };
    case 'xlsx': {
      const buf = await toXlsx(rows, columns, opts.title ?? 'Sheet1');
      return {
        body: new Uint8Array(buf),
        mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        ext: 'xlsx',
      };
    }
    case 'pdf':
      return {
        body: await toPdf(rows, columns, opts),
        mime: 'application/pdf',
        ext: 'pdf',
      };
    case 'json':
    default:
      return {
        body: JSON.stringify(rows, null, 2),
        mime: 'application/json; charset=utf-8',
        ext: 'json',
      };
  }
}
